### PR TITLE
new

### PR DESCRIPTION
**Pull request by SafaaMagdyAwad**
is it clean or complicated.

### CODE REVIEW

**Comment by Nora-Lootfy** [comment]
A little complicated

**Comment by Nora-Lootfy** [comment]
I can help you, i will create a new branch i have updated your BaseController and CarController 

**Note**, i haven't modified all your code

**Comment by Nora-Lootfy** [comment]
see the code in [this branch](https://github.com/SafaaMagdyAwad/R6laravel/tree/optimization)

**Comment by Nora-Lootfy** [comment]
notice in CarController, i have to define only store and update to make request validate if you find it hard to read DM me, if you feel it is not a good coding style forget about it.. 

it is just a little advanced approach and i am happy to learn it to someone else

**Comment by SafaaMagdyAwad** [comment]
The code is well read. I also find that this method is very useful because
it leads to writing the code once. I will do my best to get used to this
way. Thank you, my distinguished instructor.

**Comment by Nora-Lootfy** [comment]
I hope the best for you❤️ ,happy to help you always
and Thanks for your sweet words🥰@SafaaMagdyAwad

**Pull request closed without merging**
